[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sherlock"
version = "0.1.0"
description = "whatsapp lecturer directory"
requires-python = ">=3.12"

dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic"
]

[tool.setuptools.packages.find]
where = ["src"]

